project:
  type: website
  resources: 
    - Agastya_Rao_Resume (Data Science).pdf
  

website:
  title: "Agastya Rao"
  navbar:
    left:
      - href: index.qmd
        text: Home

  page-footer:
    right: "&copy; 2025, Agastya Rao"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    


